### PR TITLE
Disable private snippet option on edit page

### PR DESCRIPTION
**Pull request by taptapdan**

### CODE REVIEW

**Comment by marioyeung** [comment]
Do we declare $scope.tags before we get access to its element? When I run the program this morning it threw an error - cannot read property 0 of undefined.

**Comment by NCSkoglund** [comment]
Is there a reason why we switched from tag1/tag2/tag3 to tag[0]/tag[1]/tag[2]?  The reason I wrote it that way in the first place was to avoid ending up with empties in the tag array if somebody filled out the fields in a non-sequential order.  Otherwise, as Mario says we can just make sure that $scope.tags is defined as a global within the EditController to avoid throwing that error.

**Comment by marioyeung** [comment]
Just wanna ensure consistency - on _snippet_ we use tag1/tag2/tag3 while on _edit_ we use tag[0]/tag[1]/tag[2]. So it's better to design which way we should use to keep track of the data of tags.

**Comment by NCSkoglund** [comment]
Let's go ahead with the indexed tag[0]/tag[1]/tag[2] format for consistency.  Let me know if it's still giving errors for some reason.

**Comment by marioyeung** [comment]
We need to initialize $scope.tags as an array (empty or of length 3) before getting access to its element like this:
$scope.tags = [];
$scope.tags = [null, null, null];
There're a lot of way to implement it, and the above two are just examples. The key points are to have a declared variable and to ensure compatibility.

**Comment by taptapdan** [comment]
The reason I went with tag[0] tag[1] tag[2] for the edit page is because tags are being pulled out of the database as an array. So the tag1, tag2, tag3 references didn't work and the tag fields don't get populated with the retrieved tags.

I'm not particular re how it gets fixed. I just went with tag[0], tag[1], tag[2] because it worked.

**Pull request merged**
